# colors.ini is created/overwritten by local/share/darkman/fuzzel.sh
include=~/.config/fuzzel/colors.ini

width=32
terminal=foot -a '{cmd}' -T '{cmd}' {cmd}
filter-desktop=yes

[border]
width=2
radius=0
