export XDG_CONFIG_HOME="${HOME}/.config"
export CRAWL_DIR="${XDG_CONFIG_HOME}/crawl/"
export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/config"
export WEECHAT_HOME="${XDG_CONFIG_HOME}/weechat"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

export C_INCLUDE_PATH="${HOME}/.local/include"
export LD_LIBRARY_PATH="${HOME}/.local/lib"
export PKG_CONFIG_PATH="${HOME}/.local/lib/pkgconfig"
export MANPATH="${HOME}/.local/share/man:/usr/share/man:"
