# waylock.toml

[colors]
# Specify the initial color of the lock screen.
init_color = 0x002b36
# Specify the color of the lock screen after input is received.
input_color = 0x6c71c4
# Specify the color of the lock screen on authentication failure.
fail_color = 0xdc322f
