#!/bin/sh

# Use the "logo" key as the primary modifier
mod="Mod4"

# Normal terminal and version with large ttf font for screenshare
riverctl map normal $mod+Shift Return spawn 'foot --log-level=warning'
riverctl map normal Mod4+Shift+Control Return spawn 'foot --font=dejavusansmono:size=12 --log-level=warning'

riverctl map normal $mod Q close

# launcher
riverctl map normal $mod S spawn fuzzel.sh

# view focus
riverctl map normal $mod Return zoom
riverctl map normal $mod N focus-view next
riverctl map normal $mod E focus-view previous

# main factor/count
riverctl map normal $mod H send-layout-cmd rivertile 'main-ratio -0.05'
riverctl map normal $mod I send-layout-cmd rivertile 'main-ratio +0.05'
riverctl map normal $mod+Shift H send-layout-cmd rivertile 'main-count +1'
riverctl map normal $mod+Shift I send-layout-cmd rivertile 'main-count -1'

# move/resize
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# toggle float/fullscreen
riverctl map normal $mod Space toggle-float
riverctl map normal $mod F toggle-fullscreen

# multi-output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# screenshots
riverctl map normal $mod P spawn 'grim -g "$(slurp)" - | wl-copy'

# tags
for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod+Shift $i set-view-tags $tags
    riverctl map normal $mod+Control $i toggle-focused-tags $tags
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done
tags1to9=$(((1 << 9) - 1))
riverctl map normal $mod 0 set-focused-tags $tags1to9
riverctl map normal $mod+Shift 0 set-view-tags $tags1to9

# passthrough mode for nested sessions
riverctl declare-mode passthrough
riverctl map normal $mod Semicolon enter-mode passthrough
riverctl map passthrough $mod Semicolon enter-mode normal

riverctl set-repeat 80 300

riverctl xcursor-theme Adwaita

# float stuff with app_id "float"
riverctl float-filter-add float

riverctl default-layout rivertile

# run an svdir to supervise stuff like rivertile, foot --server, etc

# TODO: /run is mounted noexec so can't use XDG_RUNTIME_DIR
svdir="/tmp/$(id -u)-sv-${WAYLAND_DISPLAY}"

pgrep -f "^runsvdir ${svdir}" &&
    exec echo "runsvdir already running for wayland session"

# recursive, deref links, preserve mode, if target is a dir, overwrite
# instead of copying into it
cp -rLpT ~/.local/sv $svdir

exec runsvdir $svdir \
    'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
