#!/bin/sh

# Note that I use a rather unique keyboard/layout so don't expect this to
# necessarily make sense on normal keyboards.

mod="Mod4"

# Normal terminal and version with large ttf font for screenshare
riverctl map normal $mod+Mod1 Space spawn 'foot --log-level=warning'
riverctl map normal Mod4+Mod1+Shift Space spawn 'foot --font=dejavusansmono:size=16 --log-level=warning'

riverctl map normal $mod L spawn fuzzel.sh
riverctl map normal $mod+Mod1 U close

# view focus
riverctl map normal $mod Space zoom
riverctl map normal $mod E focus-view next
riverctl map normal $mod A focus-view previous

# output focus, etc.
riverctl map normal $mod H focus-output left
riverctl map normal $mod I focus-output right
riverctl map normal $mod+Mod1 H send-to-output left
riverctl map normal $mod+Mod1 I send-to-output right

# main factor/count
riverctl map normal $mod F send-layout-cmd rivertile 'main-ratio -0.05'
riverctl map normal $mod period send-layout-cmd rivertile 'main-ratio +0.05'
riverctl map normal $mod+Mod1 F send-layout-cmd rivertile 'main-count +1'
riverctl map normal $mod+Mod1 period send-layout-cmd rivertile 'main-count -1'

# move/resize
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# fullscreen/float
riverctl map normal $mod T toggle-fullscreen
riverctl map normal $mod+Mod1 T toggle-float

# screenshots
riverctl map normal $mod P spawn 'grim -g "$(slurp)" - | wl-copy'

# tags
for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod+Mod1 $i set-view-tags $tags
    riverctl map normal $mod+Mod1+Shift $i toggle-focused-tags $tags
    riverctl map normal $mod+Mod1+Shift+Control $i toggle-view-tags $tags
done
tags1to9=$(((1 << 9) - 1))
riverctl map normal $mod 0 set-focused-tags $tags1to9
riverctl map normal $mod+Mod1 0 set-view-tags $tags1to9
riverctl map normal $mod Tab focus-previous-tags
riverctl map normal $mod+Mod1 Tab send-to-previous-tags

# passthrough mode for nested sessions
riverctl declare-mode passthrough
riverctl map normal $mod+Mod1+Shift+Control Escape enter-mode passthrough
riverctl map passthrough $mod+Mod1+Shift+Control Escape enter-mode normal

riverctl set-repeat 80 300

riverctl xcursor-theme Adwaita

riverctl rule-add ssd
riverctl rule-add -app-id float float

riverctl default-layout rivertile

rivertile -view-padding 4 -outer-padding 4 &
foot --server &
swayidle -w \
	timeout 300 "waylock.sh" \
	timeout 600 "wlopm --off '*'" resume "wlopm --on '*'" &
mako &
poweralertd &
