# foot.ini

font=hack:size=13

# colors.ini is created/overwritten by local/share/darkman/foot.sh
include=~/.config/foot/colors.ini

[scrollback]
lines=4096

[key-bindings]
#scrollback-up-half-page=Control+u
#scrollback-down-half-page=Control+d
spawn-terminal=none

[cursor]
style=block
blink=no

[bell]
urgent=yes

# modus-vivendi
[colors-dark]
background=000000 # bg-main
foreground=ffffff # fg-main
regular0=ffffff # "black" fg-main
regular1=ff5f59 # "red" red
regular2=44bc44 # "green" green
regular3=d0bc00 # "yellow" yellow
regular4=2fafff # "blue" blue
regular5=feacd0 # "purple" magenta
regular6=00d3d0 # "cyan" cyan
regular7=646464 # "white" border
bright0=989898 # "bright black" fg-dim
bright1=ff5f5f # "bright red" red-intense
bright2=44df44 # "bright green" green-intense
bright3=efef00 # "bright yellow" yellow-intense
bright4=338fff # "bright blue" blue-intense
bright5=ff66ff # "bright purple" magenta-intense
bright6=00eff0 # "bright cyan" cyan-intense
bright7=535353 # "bright white" bg-active

# Use operandi bg-yellow-intense for foot's overlay UI elements
# These values seem to apply to both colors-dark and colors-light
jump-labels=000000 f3d000
search-box-match=000000 f3d000
urls=f3d000

# modus-operandi 
[colors-light]
background=ffffff # bg-main
foreground=000000 # fg-main
regular0=000000 # "black" fg-main
regular1=a60000 # "red" red
regular2=006800 # "green" green
regular3=6f5500 # "yellow" yellow
regular4=0031a9 # "blue" blue
regular5=721045 # "purple" magenta
regular6=005e8b # "cyan" cyan
regular7=9f9f9f # "white" border
bright0=595959 # "bright black" fg-dim
bright1=d00000 # "bright red" red-intense
bright2=008900 # "bright green" green-intense
bright3=808000 # "bright yellow" yellow-intense
bright4=0000ff # "bright blue" blue-intense
bright5=dd22dd # "bright purple" magenta-intense
bright6=008899 # "bright cyan" cyan-intense
bright7=c4c4c4 # "bright white" bg-active
